name: ml-blueprint
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip=23.3.1
  - pip:
      - numpy==1.26.4
      - pandas==2.2.2
      - scikit-learn==1.4.0
      - catboost==1.2.8
      - optuna==4.3.0
      - matplotlib==3.8.2
      - seaborn==0.13.1
      - jupyter==1.0.0
      - pytest==7.4.4
      - black==24.1.1
      - flake8==7.0.0
      - pyarrow==20.0.0
      - pre-commit==3.6.0
      - ydata-profiling==4.16.1
      - dash==3.0.4
      - plotly==6.1.2
      - dash-bootstrap-components==1.6.0
      - pyyaml==6.0.2
      - python-dateutil==2.8.2
      - gunicorn==23.0.0
      - flask==3.0.2
      - requests==2.31.0
